# Generated by Django 2.2.1 on 2019-09-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20190911_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(auto_now=True, null=True, verbose_name='生日'),
        ),
    ]
