# Generated by Django 2.2.1 on 2019-09-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20190912_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='num',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='book',
            name='salled',
            field=models.IntegerField(default=10),
        ),
    ]
